apiVersion: v1
kind: Pod
metadata:
  name: net-debug
  namespace: default
spec:
  nodeSelector:
    eks/self-managed: "true"
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    securityContext:
      privileged: true
